on:
    push:
        tags:
            - "v*"
        branches:
            - main

jobs:
    # Determine if this is a release
    check-release:
        runs-on: ubuntu-latest
        outputs:
            is_release: ${{ startsWith(github.ref, 'refs/tags/v') }}
            version: ${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || '' }}
        steps:
            - run: echo "Checking if this is a release build"

    # Create the targets matrix from the targets.json config file
    prepare-config:
        runs-on: ubuntu-latest
        needs: check-release
        # if: ${{ needs.check-release.outputs.is_release == 'true' }}
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - uses: actions/checkout@v4
            - name: Generate build matrix
              id: set-matrix
              run: |
                  echo 'matrix={"include": $(cat release-config/targets.json)}' >> $GITHUB_OUTPUT

    # Build binaries
    build:
        needs: [check-release, prepare-config]
        # if: ${{ needs.check-release.outputs.is_release == 'true' }}
        name: Build ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix: ${{ fromJson(needs.prepare-config.outputs.matrix) }}

        steps:
            - uses: actions/checkout@v4
            - run: echo "Building ${{ matrix.name }}"
